#include <random>
#include <iostream>
#include <cstdio>

// double desplazamiento();
 
int main()
{
  int N=4;//Repeticiones
  int Steps=10;
  int x=0;
  
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_real_distribution<> dis(0.0,  1.0);

    for(int i=1;i<=N;++i)
      {
	x=0;
    for (int n = 1; n <=Steps; ++n) {
        // Use dis to transform the random unsigned int generated by gen into a 
        // double in [1, 2). Each call to dis(gen) generates a new random double

      if(dis(gen)>0.5){
	x+=1;
	      }
      else{
		x-=1;
		
      }
      printf("%3d %3d \n",n,x);
	
      //std::cout << dis(gen) << ' ';
    }
     std::cout << '\n';
      }
    std::cout << '\n';
}

// double desplzamiento(){
//   return 0;
// }
